spring:
  datasource:
    url: jdbc:h2:~/fiapcreditcard;DB_CLOSE_ON_EXIT=FALSE
    username: fiap
    password: fiap
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  batch:
    jdbc:
      initialize-schema: always
      platform: h2
      schema: classpath:schema-h2.sql
  mvc:
    pathmatch:
      matching-strategy: "ant-path-matcher"

fiap:
  creditcard:
    resource: src/main/resources/alunos.txt

